# Query to get all the sub pages of the homepage
query HomeQuery($uri: String) {
    pageBy(uri: $uri) {
        title
        content
        # acfMeta {
        #     videoUrl
        # }
        featuredImage {
            ...homeImage
        }
    }
}

fragment homeImage on MediaItem {
    sourceUrl(size: FULLSCREEN)
    sizes(size: FULLSCREEN)
    srcSet(size: FULLSCREEN)
    id
    caption
    mediaItemId
    title
    mediaDetails {
        height
        width
    }
    acfImageMeta {
        videoUrl
        primaryColor
    }
}
