query GET_MENU($location: MenuLocationEnum) {
    menuItems(where: { location: $location }) {
        nodes {
            ...locationMenuItem
            childItems {
                nodes {
                    ...locationMenuItem
                }
            }
        }
    }
}

fragment locationMenuItem on MenuItem {
    label
    cssClasses
    target
    url
}
