menus {
    nodes {
      id
      menuId
      menuItems {
        edges {
          node {
            id
            menuItemId
            title
            url
            connectedObject {
              __typename
            }
            cssClasses
            description
            label
            linkRelationship
            target
          }
        }
        nodes {
          id
          menuItemId
          title
          url
          connectedObject {
            __typename
          }
          cssClasses
          description
          label
          linkRelationship
          target
        }
      }
    }
}
