query GET_POST($first: Int){
    posts(first: $first) {
            edges {
                node {
                  id
                  title
                  date
                  content
                  featuredImage {
                      id
                      link
                      caption
                      altText
                      description
                      mediaType
                      sourceUrl
                      mediaDetails{
                        width
                        height
                        file
                        sizes{
                          name
                          file
                          width
                          height
                          mimeType
                          sourceUrl
                        }
                    }
                }
            }
        }
    }
}
