query GET_POST($first: Int){
    posts(first: $first) {
            edges {
                node {
                  id
                  title
                  date
                }
            }
        }
    }
