# Query page by dev id meta field
query GET_PAGE_BY_DEV_ID($devId: String) {
    pages(
        where: {
            metaQuery: {
                metaArray: [
                    {
                        key: "custom_developer_id"
                        value: $devId
                        compare: EQUAL_TO
                    }
                ]
            }
        }
        first: 1
    ) {
        edges {
            node {
                id
                pageId
                title
                content
                link
                date
            }
        }
    }
}
