#import "~/gql/fragments/MediaImage.gql"

fragment GutenbergBlocks on BlockEditorContentNode {
    blocks {
        name

        ...FreeformBlock
        ...ParagraphBlock
        ...ImageBlock
        ...EmbedBlock
        ...GalleryBlock
        ...HeadingBlock
        ...QuoteBlock
        ...ListBlock
        ...SpacerBlock
        ...CoverBlock
        ...HtmlBlock
        ...VideoBlock
        ...ButtonsBlock

        # Columns (and column)
        ...ColumnsBlock
    }
}

# Legacy content
fragment FreeformBlock on Block {
    ... on CoreFreeformBlock {
        attributes {
            ... on CoreFreeformBlockAttributes {
                html: content
            }
        }
    }
}

# Image
fragment ImageBlock on Block {
    ... on CoreImageBlock {
        attributes {
            ... on CoreImageBlockAttributes {
                caption
                wpId: anchor
                wpClasses: className
                align
                size: sizeSlug
                widthPixels: width
            }
        }
        mediaItem {
            node {
                ...MediaImage
            }
        }
    }
}

# Paragraph
fragment ParagraphBlock on Block {
    ... on CoreParagraphBlock {
        attributes {
            ... on CoreParagraphBlockAttributes {
                content
                textAlign: align
                fontSize: fontSizeValue
                textColor: textColorCode
                backgroundColor: backgroundColorCode
                dropCap
                wpId: anchor
                wpClasses: className
            }
        }
    }
}

# Video
fragment VideoBlock on Block {
    ... on CoreVideoBlock {
        attributes {
            ... on CoreVideoBlockAttributes {
                src
                muted
                autoplay
                controls
                loop
                preload
                poster
                align
                wpId: anchor
                wpClasses: className
            }
        }
    }
}

# Embeds (YouTube and Vimeo)
fragment EmbedBlock on Block {
    ... on CoreEmbedBlock {
        attributes {
            ... on CoreEmbedBlockAttributes {
                provider: providerNameSlug
                url
                caption
                wpClasses: className
            }
        }
    }
}

# Galleries
fragment GalleryBlock on Block {
    ... on CoreGalleryBlock {
        innerBlocks {
            ... on CoreImageBlock {
                mediaItem {
                    node {
                        ...MediaImage
                    }
                }
            }
        }
        attributes {
            ... on CoreGalleryBlockAttributes {
                columns
                imageCrop
                caption
                wpId: anchor
                wpClasses: className
            }
        }
    }
}

# Headings
fragment HeadingBlock on Block {
    ... on CoreHeadingBlock {
        attributes {
            ... on CoreHeadingBlockAttributes {
                content
                level
                textAlign
                className
                fontSize
                textColor: textColorCode
                backgroundColor: backgroundColorCode
                wpId: anchor
                wpClasses: className
            }
        }
    }
}

# Blockquotes
fragment QuoteBlock on Block {
    ... on CoreQuoteBlock {
        attributes {
            ... on CoreQuoteBlockAttributes {
                citation
                wpId: anchor
                wpClasses: className
                textAlign: align
                textColor: textColorCode
                backgroundColor: backgroundColorCode
                fontSize: fontSizeValue
            }
        }
        innerBlocks {
            ...ParagraphBlock
        }
    }
}

# UL and OL lists
fragment ListBlock on Block {
    ... on CoreListBlock {
        attributes {
            ... on CoreListBlockAttributes {
                ordered
                fontSize
                textColor: textColorCode
                backgroundColor: backgroundColorCode
            }
        }
        innerBlocks {
            ... on CoreListItemBlock {
                attributes {
                    ... on CoreListItemBlockAttributes {
                        content
                        wpClasses: className
                    }
                }
            }
        }
    }
}

# Spacer block
fragment SpacerBlock on Block {
    ... on CoreSpacerBlock {
        attributes {
            ... on CoreSpacerBlockAttributes {
                height
                wpId: anchor
                wpClasses: className
            }
        }
    }
}

# Columns
fragment ColumnsBlock on Block {
    ... on CoreColumnsBlock {
        attributes {
            ... on CoreColumnsBlockAttributes {
                wpId: anchor
                wpClasses: className
            }
        }
        blocks: innerBlocks {
            # Columns will always have a direct column block child, but this handles nested columns
            ...ColumnBlock

            ... on CoreColumnBlock {
                blocks: innerBlocks {
                    name
                    ... on CoreColumnsBlock {
                        attributes {
                            ... on CoreColumnsBlockAttributes {
                                wpId: anchor
                                wpClasses: className
                            }
                        }
                        blocks: innerBlocks {
                            ...ColumnBlock
                        }
                    }
                }
            }
        }
    }
}

# Column (used inside Columns)
fragment ColumnBlock on Block {
    ... on CoreColumnBlock {
        name
        attributes {
            ... on CoreColumnBlockAttributes {
                width
                verticalAlignment
            }
        }
        blocks: innerBlocks {
            name
            ...HeadingBlock
            ...ParagraphBlock
            ...ImageBlock
            ...QuoteBlock
            ...SpacerBlock
            ...HtmlBlock
            ...ListBlock
            ...EmbedBlock
            ...VideoBlock
            ...ButtonsBlock
        }
    }
}

# Cover
fragment CoverBlock on Block {
    ... on CoreCoverBlock {
        blocks: innerBlocks {
            name
            ...HeadingBlock
            ...ParagraphBlock
            ...ImageBlock
            ...ColumnsBlock
        }
        attributes {
            ... on CoreCoverBlockAttributes {
                align
                backgroundType
                contentPosition
                customGradient
                customOverlayColor
                opacity: dimRatio
                gradient
                minHeight
                minHeightUnit
                overlayColor
                url
                isFixed: hasParallax
                wpId: anchor
                wpClasses: className
            }
        }
    }
}

# Html
fragment HtmlBlock on Block {
    ... on CoreHtmlBlock {
        html: originalContent
    }
}

# Buttons (group)
fragment ButtonsBlock on Block {
    ... on CoreButtonsBlock {
        attributes {
            ... on CoreButtonsBlockAttributes {
                wpId: anchor
                layout
                fontSize: fontSizeValue
                wpClasses: className
            }
        }
        innerBlocks {
            name
            ...ButtonBlock
        }
    }
}

# Button (single)
fragment ButtonBlock on Block {
    ... on CoreButtonBlock {
        attributes {
            ... on CoreButtonBlockAttributes {
                wpId: anchor
                fontSize: fontSizeValue
                text
                styles: style
                target: linkTarget
                wpClasses: className
                backgroundColor: backgroundColorCode
                textColor: textColorCode
                url
                widthPercentage: width
            }
        }
    }
}
