#import "~/gql/fragments/MediaImage.gql"

fragment GutenbergColumns on CoreColumnsBlock {
    blocks: innerBlocks {
        # Columns will always have a direct column block child, but this handles nested columns
        ... on CoreColumnBlock {
            ...GutenbergColumn
            blocks: innerBlocks {
                name
                ... on CoreColumnsBlock {
                    blocks: innerBlocks {
                        ... on CoreColumnBlock {
                            ...GutenbergColumn
                        }
                    }
                }
            }
        }
    }
}

fragment GutenbergColumn on CoreColumnBlock {
    name
    attributes {
        ... on CoreColumnBlockAttributes {
            width
            verticalAlignment
        }
    }
    blocks: innerBlocks {
        name

        # Heading
        ... on CoreHeadingBlock {
            attributes {
                ... on CoreHeadingBlockAttributes {
                    content
                    level
                    textAlign
                    fontSize
                    textColor
                    className
                    backgroundColor
                }
            }
        }

        # Paragraph
        ... on CoreParagraphBlock {
            attributes {
                ... on CoreParagraphBlockAttributes {
                    className
                    content
                    align
                    fontSize
                    textColor
                }
            }
        }

        # Image
        ... on CoreImageBlock {
            attributes {
                ... on CoreImageBlockAttributes {
                    caption
                }
            }
            mediaItem {
                nodes {
                    ...MediaImage
                }
            }
        }
    }
}
