fragment MediaImage on MediaItem {
    sourceUrl(size: FULLSCREEN)
    sizes(size: FULLSCREEN)
    srcSet(size: FULLSCREEN)
    id
    databaseId
    title
    altText
    caption
    mediaDetails {
        height
        width
    }
    acfImageMeta {
        videoUrl
        primaryColor
        focalPointX
        focalPointY
    }
}
