query MenuByName($name: ID!) {
    menu(id: $name, idType: NAME) {
        id
        name
        menuItems(first: 30) {
            nodes {
                ...MenuItem
            }
        }
    }
}

fragment MenuItem on MenuItem {
    label
    cssClasses
    target
    url
    id
}
