query WpControls($uri: String!) {
    nodeByUri(uri: $uri) {
        id
        __typename
        ... on ContentNode {
            databaseId
        }
    }
    viewer {
        id
        nicename
        avatar(size: 20) {
            url
            width
            height
        }
    }
}
