#import "~/gql/fragments/MediaImage.gql"
#import "~/gql/fragments/GutenbergBlocks.gql"

# Query to get all the sub pages of the homepage
query Home($uri: String!) {
    nodeByUri(uri: $uri) {
        ... on Page {
            title
            id
            # workMeta {
            #     videoUrl
            # }
            featuredImage {
                node {
                    ...MediaImage
                }
            }
            ...GutenbergBlocks
        }
    }
}
