#import "~/gql/fragments/MediaImage.gql"

# Query to get all the sub pages of the homepage
query Home($uri: String!) {
    nodeByUri(uri: $uri) {
        ... on Page {
            title
            content
            id
            # acfMeta {
            #     videoUrl
            # }
            featuredImage {
                ...MediaImage
            }
        }
    }
}
