query MenuByLocation($location: MenuLocationEnum) {
    menuItems(first: 99, where: { location: $location, parentDatabaseId: 0 }) {
        nodes {
            ...LocationMenuItem
            childItems {
                nodes {
                    ...LocationMenuItem
                }
            }
        }
    }
}

fragment LocationMenuItem on MenuItem {
    label
    cssClasses
    target
    url
    id
}
