#import "~/gql/fragments/MediaImage.gql"

query NEWS_LIST($categoryName: String = null) {
    posts(where: { categoryName: $categoryName }, first: 20) {
        nodes {
            id
            uri
            title
            encodedContent
            date
            featuredImage {
                node {
                    ...MediaImage
                }
            }
        }
    }
}
