#import "~/gql/fragments/MediaImage.gql"

query Seo($uri: String!) {
    nodeByUri(uri: $uri) {
        id
        ... on NodeWithTitle {
            title
        }
        ... on NodeWithContentEditor {
            content
        }
        ... on NodeWithExcerpt {
            excerpt
        }
        ... on NodeWithFeaturedImage {
            featuredImage {
                node {
                    ...MediaImage
                }
            }
        }
    }
}
