query WpSettings {
    # This syntax is called a GQL alias. See: https://graphql.org/learn/queries/#aliases
    wpSettings: generalSettings {
        title
        description
        url
        siteUrl
        themeScreenshotUrl
    }
    acfSettings: siteOptions {
        acfSiteOptions {
            socialMedia {
                platform
                url
            }
            googleAnalytics {
                code
            }
        }
    }
}
