query SiteSettings {
    # This syntax is called a GQL alias. See: https://graphql.org/learn/queries/#aliases
    wpSettings: generalSettings {
        title
        description
        backendUrl
        frontendUrl
        themeScreenshotUrl
    }
    # NOTE You need ACF Pro installed to use Site Options
    acfSettings: siteOptions {
        acfSiteOptions {
            socialMedia {
                platform
                url
            }
            googleAnalytics {
                code
            }
        }
    }
}
