query WpSettings {
    generalSettings {
        title
        description
        url
        siteUrl
        themeScreenshotUrl
    }
}

query SiteOptions {
    siteOptions {
        acfSiteOptions {
            socialMedia {
                platform
                url
            }
            googleAnalytics {
                code
            }
        }
    }
}
